In [45]:
# fundamental libraries
import numpy as np
import pandas as pd

# visualization
import matplotlib.pyplot as plt
import seaborn as sns

# utils
from utils.save_result import *
from utils.visualization import *
from utils.test_functions import *
from utils.engineering_problem import *
from utils.ourmodel import *

In [46]:
human_model_names = ["OriginalBSO", "OriginalCA", "OriginalCHIO", "OriginalFBIO", "OriginalLCO", 
                     "OriginalSARO", "OriginalSPBO", "OriginalSSDO", "OriginalTLO", "Model"]

### CLASSICAL TEST FUNCTION

In [47]:
f_names = ["F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12", "F13", "F14", "F15", "F16"]

f_function = ["Ackley2", "Brent", "ChungReynolds", "Cigar", "Matyas", "Leon", "Michalewicz", "CrossInTray", 
                   "Hosaki", "Langermann", "Levy5", "Mishra5", "Alpine2","Hansen", "Himmelblau", "Chichinadze"]

#### Get Statistical Results

In [48]:
best_fit_statistic(test_folder="human/classic", test_names=f_names, models=human_model_names)

                        BSO        CA      CHIO      FBIO       LCO     Model  \
Problem Statictic
F1      min        0.013369  0.000000  1.000000  0.000000  0.000000  0.000000
        std        0.004755  0.113087  1.000000  0.000000  0.000000  0.000000
F10     min        0.001636  0.000000  1.000000  0.000000  0.000000  0.000063
        std        0.001022  1.000000  0.173671  0.000000  0.988231  0.017044
F11     min        0.000925  0.000000  1.000000  0.000000  0.000000  0.000051
        std        0.122495  1.000000  0.852345  0.000000  0.857696  0.001180
F12     min        0.008881  1.000000  0.000028  0.000000  0.000000  0.000000
        std        0.032637  1.000000  0.195242  0.000000  0.000000  0.000004
F13     min        0.000273  0.000000  0.059676  0.000000  0.000000  0.000003
        std        0.000452  0.086727  0.109574  0.000000  0.000000  0.000064
F14     min        0.013335  0.000000  1.000000  0.000002  0.000000  0.012862
        std        0.037004  1.000000  0.516119  0.000268  0.000000  0.002311
F15     min        0.000501  0.000000  0.325727  0.000000  0.000000  0.000006
        std        0.004123  0.192085  0.233264  0.000003  0.000000  0.000408
F16     min        0.003184  0.000000  1.000000  0.000000  0.000000  0.000009
        std        0.101551  0.051864  1.000000  0.000000  0.165827  0.112340
F2      min        0.002720  1.000000  0.000000  0.000000  0.000000  0.000000
        std        0.000846  1.000000  0.000000  0.000000  0.000000  0.000000
F3      min        0.000000  0.000000  1.000000  0.000000  0.000000  0.000000
        std        0.000000  0.003761  1.000000  0.000000  0.000000  0.000000
F4      min        0.008588  0.000000  1.000000  0.000000  0.000000  0.000000
        std        0.026285  0.000147  1.000000  0.000000  0.000000  0.000000
F5      min        0.000960  0.000000  1.000000  0.000000  0.000000  0.000122
        std        0.000461  0.000001  1.000000  0.000000  0.000000  0.000053
F6      min        0.013693  0.000000  1.000000  0.000002  0.000000  0.000021
        std        0.023062  1.000000  0.553908  0.000002  0.000000  0.053219
F7      min        0.001883  0.000000  0.356789  0.000000  0.000000  0.000012
        std        0.003383  0.118527  0.250011  0.000000  0.000000  0.000055
F8      min        0.000214  0.000000  1.000000  0.000000  0.000000  0.000012
        std        0.001531  0.022746  1.000000  0.000000  0.000000  0.000284
F9      min        0.000584  0.000000  0.785790  0.000000  0.000000  0.000034
        std        0.000814  0.006890  0.100228  0.000000  0.000000  0.000021

                       SARO      SPBO      SSDO       TLO
Problem Statictic
F1      min        0.000000  0.000000  0.000033  0.000000
        std        0.000000  0.000000  0.011125  0.000000
F10     min        0.000000  0.000000  0.085889  0.000000
        std        0.000000  0.000000  0.541704  0.000000
F11     min        0.000000  0.000000  0.110805  0.000000
        std        0.000000  0.436781  0.501974  0.000004
F12     min        0.000000  0.000000  0.000004  0.000000
        std        0.000000  0.000000  0.005855  0.000000
F13     min        0.000000  0.000000  1.000000  0.000000
        std        0.000000  0.000000  1.000000  0.000000
F14     min        0.000000  0.000000  0.260204  0.006590
        std        0.008949  0.000000  0.649862  0.033422
F15     min        0.000000  0.000000  1.000000  0.000000
        std        0.000000  0.000000  1.000000  0.000002
F16     min        0.000000  0.000000  0.049481  0.000000
        std        0.000000  0.162606  0.096242  0.000000
F2      min        0.000000  0.000000  0.000000  0.000000
        std        0.000000  0.000000  0.000000  0.000000
F3      min        0.000000  0.000000  0.000000  0.000000
        std        0.000000  0.000000  0.000000  0.000000
F4      min        0.000000  0.000000  0.000017  0.000000
        std        0.000000  0.000000  0.001558  0.000000
F5      min        0.000000  0.000000  0.000000  0.000000
        std        0.000000  0.000000  0.000017  0.000000
F6      min        0.000000  0.000000  0.684047  0.000085
        std        0.000000  0.000000  0.950413  0.000045
F7      min        0.000000  0.000000  1.000000  0.000000
        std        0.000000  0.000000  1.000000  0.000000
F8      min        0.000000  0.000000  0.008080  0.000000
        std        0.000000  0.000000  0.027877  0.000003
F9      min        0.000000  0.000000  1.000000  0.000000
        std        0.000000  0.000000  1.000000  0.000000

#### Compare Models by Ranking

In [49]:
best_fitness(test_folder="human/classic", test_names=f_names, models=human_model_names)

In [50]:
compute_rank(test_folder="human/classic", test_names=f_names)

   Problem   BSO     CA   CHIO  FBIO   LCO  SARO  SPBO   SSDO   TLO  Model
0       F1  8.72   2.56  10.00  1.00  1.00  1.00  1.00   8.16  1.00   1.00
1       F2  9.00  10.00   1.00  1.00  1.00  1.00  1.00   1.00  1.00   1.00
2       F3  1.00   1.96  10.00  1.00  1.00  1.00  1.00   1.84  1.00   1.00
3       F4  9.00   1.24  10.00  1.00  1.00  1.00  1.00   8.00  1.00   1.00
4       F5  8.36   1.00  10.00  1.00  1.00  1.00  1.00   1.48  1.00   3.80
5       F6  6.92   8.60   8.56  1.00  1.00  1.00  1.00   9.56  4.68   5.64
6       F7  7.80   2.88   9.00  1.00  1.00  1.00  1.00  10.00  1.00   5.28
7       F8  7.24   4.60  10.00  1.00  1.00  1.00  1.00   9.00  1.00   3.20
8       F9  7.96   1.48   9.00  1.00  1.00  1.00  1.00  10.00  1.00   5.76
9      F10  7.24   6.48   8.56  1.00  1.64  1.00  1.00   9.48  1.00   6.04
10     F11  7.04   5.64  10.00  1.04  3.48  1.00  1.52   8.28  3.28   6.00
11     F12  8.28  10.00   8.68  1.00  1.00  1.00  1.00   7.00  1.00   3.60
12     F13  7.68   3.92   9.00  1.00  1.00  1.00  1.00  10.00  1.00   5.88
13     F14  6.80   7.88   8.68  3.08  1.00  3.92  1.00   9.60  6.36   4.92
14     F15  7.60   4.76   8.96  1.48  1.00  1.00  1.00  10.00  1.24   6.24
15     F16  6.88   1.36  10.00  1.00  4.24  1.00  4.76   7.80  1.00   6.48

#### Compare Models by Signed Test

In [51]:
classic = signed_test(test_folder="human/classic", test_names=f_names, trial_size=25)
classic

  Model2  (+)  (-)  Trials
0    BSO   33  367     400
1     CA  116  284     400
2   CHIO    1  399     400
3   FBIO  241  159     400
4    LCO  219  181     400
5   SARO  233  167     400
6   SPBO  227  173     400
7   SSDO   14  386     400
8    TLO  218  182     400

### CEC22 FUNCTION

In [52]:
c_names = ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11", "C12"]
c_function = ["F12022", "F22022", "F32022", "F42022", "F52022", "F62022", "F72022", 
              "F82022", "F92022", "F102022", "F112022", "F122022"]

#### Get Statistical Results

In [53]:
best_fit_statistic(test_folder="human/cec22", test_names=c_names, models=human_model_names)

                        BSO        CA      CHIO      FBIO       LCO     Model  \
Problem Statictic
C1      min        0.199689  0.008694  1.000000  0.000000  0.057207  0.000251
        std        0.462727  0.540701  1.000000  0.000000  0.304844  0.001119
C10     min        0.311428  1.000000  0.549310  0.184863  0.288548  0.048289
        std        0.784713  0.000000  0.488387  0.646134  0.823413  1.000000
C11     min        0.000000  1.000000  0.934991  0.481914  0.322458  0.094921
        std        0.821331  0.000000  0.137316  0.506249  0.670796  1.000000
C12     min        0.792083  0.996288  0.528846  0.489406  0.737460  0.000000
        std        1.000000  0.274092  0.572803  0.228107  0.682770  0.629172
C2      min        0.407670  0.070065  0.348903  0.000000  0.031106  0.003420
        std        1.000000  0.067508  0.616632  0.037745  0.179789  0.052635
C3      min        0.193196  0.002268  0.775382  0.000000  0.032249  0.000114
        std        0.606292  0.061677  1.000000  0.000000  0.273212  0.000657
C4      min        0.159788  0.028828  1.000000  0.000000  0.098596  0.078217
        std        1.000000  0.723151  0.854304  0.000000  0.457635  0.329574
C5      min        0.180265  0.004854  1.000000  0.000003  0.111602  0.004517
        std        0.694295  0.312360  1.000000  0.316276  0.907051  0.493974
C6      min        0.000126  0.000017  0.103449  0.000000  0.000218  0.000136
        std        0.125819  0.003801  0.260551  0.000017  0.000089  0.000133
C7      min        0.061968  0.000000  0.488207  0.001280  0.021287  0.055992
        std        0.663535  0.223786  1.000000  0.000000  0.116950  0.156090
C8      min        0.189908  0.018860  1.000000  0.000000  0.036930  0.048794
        std        0.000001  0.000000  0.077675  0.000000  0.000000  0.000001
C9      min        0.469439  0.007705  0.756096  0.000000  0.084732  0.002939
        std        1.000000  0.809107  0.576702  0.692066  0.654077  0.854403

                       SARO      SPBO      SSDO       TLO
Problem Statictic
C1      min        0.000597  0.173617  0.524463  0.000013
        std        0.000978  0.424351  0.395489  0.000110
C10     min        0.273732  0.000000  0.784250  0.500455
        std        0.580224  0.792928  0.207700  0.430213
C11     min        0.900463  0.066210  0.704192  0.695240
        std        0.079827  0.588568  0.240565  0.363867
C12     min        0.821004  0.610434  1.000000  0.834383
        std        0.002730  0.313603  0.690533  0.000000
C2      min        0.002912  0.292527  1.000000  0.000211
        std        0.000000  0.192874  0.751065  0.001564
C3      min        0.000018  0.198746  1.000000  0.000000
        std        0.000040  0.373285  0.647564  0.000010
C4      min        0.126737  0.083567  0.353944  0.132975
        std        0.209254  0.771070  0.428706  0.342471
C5      min        0.000350  0.162057  0.572360  0.000000
        std        0.000557  0.518862  0.499759  0.000000
C6      min        0.000032  0.000049  1.000000  0.000112
        std        0.000000  0.005812  1.000000  0.000069
C7      min        0.055849  0.006866  1.000000  0.032966
        std        0.021137  0.090686  0.875089  0.024110
C8      min        0.006475  0.038961  0.764805  0.018366
        std        0.000000  0.000000  1.000000  0.000000
C9      min        0.002552  0.210303  1.000000  0.000105
        std        0.000000  0.524423  0.604469  0.394821

#### Compare Models by Ranking

In [54]:
best_fitness(test_folder="human/cec22", test_names=c_names, models=human_model_names)

In [55]:
compute_rank(test_folder="human/cec22", test_names=c_names)

   Problem   BSO    CA   CHIO  FBIO   LCO  SARO  SPBO   SSDO   TLO  Model
0       C1  7.88  5.80  10.00  1.00  5.32  3.88  7.04   8.96  2.00   3.12
1       C2  8.24  5.32   9.00  1.32  5.72  2.80  6.96   9.76  1.88   4.00
2       C3  7.96  5.00   9.56  1.00  6.00  3.00  7.04   9.44  1.52   4.00
3       C4  8.48  5.36  10.00  1.00  2.48  4.60  4.04   8.48  6.08   4.48
4       C5  7.72  3.96  10.00  2.80  6.16  2.28  7.00   8.96  1.00   5.12
5       C6  5.28  3.20   9.00  1.92  6.48  1.12  6.56  10.00  4.40   7.04
6       C7  8.00  4.28   9.00  1.08  4.28  3.52  5.20  10.00  2.84   6.80
7       C8  7.84  4.00   9.16  1.08  4.96  1.92  6.04   9.84  3.04   7.12
8       C9  8.68  4.84   8.40  1.56  5.84  2.36  6.96   9.92  2.08   4.36
9      C10  6.84  9.52   5.36  2.00  7.56  5.36  1.76   8.84  5.32   2.44
10     C11  6.20  9.92   5.24  1.88  6.68  6.28  2.88   8.76  5.44   1.72
11     C12  9.24  7.28   7.20  2.56  5.84  2.88  5.48   9.52  1.56   3.44

#### Compare Models by Signed Test

In [56]:
cec22 = signed_test(test_folder="human/cec22", test_names=c_names, trial_size=25)
cec22

  Model2  (+)  (-)  Trials
0    BSO   49  251     300
1     CA  102  198     300
2   CHIO   12  288     300
3   FBIO  250   50     300
4    LCO  105  195     300
5   SARO  206   94     300
6   SPBO  102  198     300
7   SSDO   10  290     300
8    TLO  222   78     300

### RESULTS OF ALL TESTS

The comparison of the ACSA model and other methods is as follows. (-) indicates how many of the results have the minimum value, that is, the WINNING score.

In [57]:
all = classic + cec22 
all

     Model2  (+)  (-)  Trials
0    BSOBSO   82  618     700
1      CACA  218  482     700
2  CHIOCHIO   13  687     700
3  FBIOFBIO  491  209     700
4    LCOLCO  324  376     700
5  SAROSARO  439  261     700
6  SPBOSPBO  329  371     700
7  SSDOSSDO   24  676     700
8    TLOTLO  440  260     700

In [58]:
classic.to_csv('results/human_classic.csv', index=False)
cec22.to_csv('results/human_cec.csv', index=False)
all.to_csv('results/human_total.csv', index=False)