In [43]:
# fundamental libraries
import numpy as np
import pandas as pd

# visualization
import matplotlib.pyplot as plt
import seaborn as sns

# utils
from utils.save_result import *
from utils.visualization import *
from utils.test_functions import *
from utils.engineering_problem import *
from utils.ourmodel import *

In [44]:
physics_model_names = ["OriginalASO", "OriginalCDO", "OriginalEFO", "OriginalEO", "OriginalHGSO", "OriginalMVO", 
                     "OriginalNRO", "OriginalSA", "OriginalWDO", "Model"]

### CLASSICAL TEST FUNCTION

In [45]:
f_names = ["F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12", "F13", "F14", "F15", "F16"]

f_function = ["Ackley2", "Brent", "ChungReynolds", "Cigar", "Matyas", "Leon", "Michalewicz", "CrossInTray", 
                   "Hosaki", "Langermann", "Levy5", "Mishra5", "Alpine2","Hansen", "Himmelblau", "Chichinadze"]

#### Get Statistical Results

In [46]:
best_fit_statistic(test_folder="physics/classic", test_names=f_names, models=physics_model_names)

                        ASO       CDO       EFO        EO      HGSO       MVO  \
Problem Statictic
F1      min        0.056771  0.000000  0.151827  0.000000  0.646088  0.003206
        std        0.168158  0.000000  0.797208  0.000000  0.186484  0.003897
F10     min        0.664676  0.009436  0.699422  0.000000  0.023420  0.000403
        std        0.075561  0.056770  0.834037  0.000000  0.203087  0.394670
F11     min        0.088631  1.000000  0.107546  0.000000  0.050176  0.000024
        std        0.405175  0.865398  1.000000  0.206376  0.795682  0.787871
F12     min        0.024809  1.000000  0.169106  0.000000  0.569576  0.000000
        std        0.015726  1.000000  0.401616  0.000000  0.206835  0.000000
F13     min        0.050647  0.102770  0.449528  0.000000  1.000000  0.000232
        std        0.017936  0.030307  0.684947  0.000000  0.143175  0.000071
F14     min        0.151366  0.142131  1.000000  0.000000  0.319908  0.000003
        std        0.098961  0.319812  1.000000  0.000000  0.583811  0.000454
F15     min        0.035041  0.267822  0.186277  0.000000  1.000000  0.000199
        std        0.009053  0.008467  1.000000  0.000000  0.250425  0.000016
F16     min        0.082049  0.001533  0.272520  0.000000  1.000000  0.000061
        std        0.038746  0.035002  1.000000  0.000000  0.180943  0.000087
F2      min        0.000315  0.015640  0.034064  0.000000  0.000000  0.000000
        std        0.001813  0.774982  0.264147  0.000000  0.055705  0.000000
F3      min        0.000087  0.000000  0.564459  0.000000  0.279151  0.000000
        std        0.000110  0.000000  0.041444  0.000000  0.000987  0.000000
F4      min        0.048744  0.000000  0.134758  0.000000  1.000000  0.000013
        std        0.000810  0.000000  1.000000  0.000000  0.046248  0.000005
F5      min        0.000274  0.000000  0.891686  0.000000  1.000000  0.000007
        std        0.009263  0.000000  1.000000  0.000000  0.047376  0.000008
F6      min        0.013099  0.147302  1.000000  0.000000  0.357930  0.000001
        std        0.005588  0.032255  0.707297  0.000002  0.088574  0.000009
F7      min        0.013011  0.072577  0.021718  0.000000  1.000000  0.000037
        std        0.044490  0.058496  0.420135  0.000000  0.301492  0.000069
F8      min        0.035099  0.000347  0.308476  0.000000  1.000000  0.000070
        std        0.013577  0.001640  0.257300  0.000000  0.181736  0.000044
F9      min        0.021611  0.025898  1.000000  0.000000  0.168808  0.000013
        std        0.013832  0.018676  0.583673  0.000000  0.176864  0.000039

                      Model       NRO        SA       WDO
Problem Statictic
F1      min        0.000000  0.000000  1.000000  0.000002
        std        0.000000  0.000000  1.000000  0.000140
F10     min        0.000026  0.000000  0.197599  1.000000
        std        0.008736  0.000000  1.000000  0.631404
F11     min        0.000009  0.000000  0.003513  0.287609
        std        0.000610  0.000000  0.956534  0.903239
F12     min        0.000000  0.000024  0.361588  0.345064
        std        0.000001  0.000047  0.704384  0.338490
F13     min        0.000004  0.000000  0.016190  0.194547
        std        0.000044  0.000000  1.000000  0.063307
F14     min        0.002977  0.003658  0.081727  0.911797
        std        0.000786  0.005297  0.688015  0.876842
F15     min        0.000063  0.000110  0.376258  0.869308
        std        0.000089  0.000016  0.533191  0.060521
F16     min        0.000002  0.000000  0.999985  0.941883
        std        0.037408  0.000000  0.963930  0.777461
F2      min        0.000000  0.000000  0.300042  1.000000
        std        0.000000  0.000000  1.000000  0.750892
F3      min        0.000000  0.000000  1.000000  0.000000
        std        0.000000  0.000000  1.000000  0.065891
F4      min        0.000000  0.000000  0.079353  0.000000
        std        0.000000  0.000000  0.740529  0.000411
F5      min        0.000018  0.000000  0.438894  0.000000
        std        0.000010  0.000000  0.875639  0.000000
F6      min        0.000011  0.000002  0.115146  0.207325
        std        0.009654  0.000000  1.000000  0.061436
F7      min        0.000013  0.000000  0.699735  0.057724
        std        0.000051  0.000000  1.000000  0.122541
F8      min        0.000010  0.000001  0.084187  0.145935
        std        0.000078  0.000002  1.000000  0.257542
F9      min        0.000022  0.000000  0.196659  0.093759
        std        0.000022  0.000000  1.000000  0.317992

#### Compare Models by Ranking

In [47]:
best_fitness(test_folder="physics/classic", test_names=f_names, models=physics_model_names)

In [48]:
compute_rank(test_folder="physics/classic", test_names=f_names)

   Problem   ASO   CDO   EFO    EO  HGSO   MVO   NRO     SA   WDO  Model
0       F1  7.00  1.00  8.64  1.00  8.36  6.00  1.00  10.00  5.00   1.00
1       F2  5.44  9.04  7.04  1.00  3.80  1.00  1.36   8.44  9.48   1.00
2       F3  6.96  1.00  9.04  1.00  8.04  1.48  1.00   9.84  2.52   1.00
3       F4  7.00  1.00  9.92  1.00  8.88  5.12  1.00   8.20  5.88   1.00
4       F5  6.76  1.00  9.76  1.00  8.16  3.24  1.00   9.08  1.00   2.64
5       F6  4.88  6.04  9.96  1.04  8.12  2.28  1.08   8.80  7.08   3.88
6       F7  5.28  5.80  8.12  1.00  9.00  3.76  1.00   9.76  7.04   2.52
7       F8  6.16  4.84  9.00  1.00  8.20  2.44  1.00   9.68  6.96   1.92
8       F9  5.24  5.92  9.56  1.00  8.32  3.68  1.00   9.08  6.88   2.60
9      F10  6.32  4.96  9.68  1.00  7.92  4.04  1.00   8.96  7.04   3.00
10     F11  4.80  9.68  8.84  1.08  6.72  4.36  1.92   7.00  7.60   2.96
11     F12  5.00  9.92  6.88  1.00  6.52  1.52  4.00   8.96  7.72   1.56
12     F13  5.04  6.04  9.92  1.00  8.80  4.00  1.00   7.64  7.56   2.76
13     F14  5.88  6.08  9.80  1.00  7.88  2.00  4.00   6.28  9.08   3.00
14     F15  5.24  5.80  9.84  1.00  8.60  2.88  2.00   8.44  7.08   3.88
15     F16  6.00  4.88  9.72  1.00  7.76  3.08  1.00   7.60  8.92   4.04

#### Compare Models by Signed Test

In [49]:
classic = signed_test(test_folder="physics/classic", test_names=f_names, trial_size=25)
classic

  Model2  (+)  (-)  Trials
0    ASO   13  387     400
1    CDO   20  380     400
2    EFO    0  400     400
3     EO  240  160     400
4   HGSO    3  397     400
5    MVO  131  269     400
6    NRO  197  203     400
7     SA    2  398     400
8    WDO   13  387     400

### CEC22 FUNCTION

In [50]:
c_names = ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11", "C12"]
c_function = ["F12022", "F22022", "F32022", "F42022", "F52022", "F62022", "F72022", 
              "F82022", "F92022", "F102022", "F112022", "F122022"]

#### Get Statistical Results

In [51]:
best_fit_statistic(test_folder="physics/cec22", test_names=c_names, models=physics_model_names)

                        ASO       CDO       EFO        EO      HGSO       MVO  \
Problem Statictic
C1      min        0.266819  0.709411  0.991516  0.000000  0.699949  0.000022
        std        0.135359  0.135735  0.784146  0.000053  0.271974  0.000000
C10     min        0.588184  0.892740  1.000000  0.000000  0.729130  0.043292
        std        0.284977  0.000000  0.297466  0.918976  0.017427  1.000000
C11     min        0.674713  0.785097  1.000000  0.448894  0.909658  0.000000
        std        0.228938  0.126252  0.297434  0.248732  0.000000  1.000000
C12     min        0.548307  1.000000  0.686074  0.541395  0.738172  0.565805
        std        0.148798  0.640366  0.293279  0.000000  0.372279  0.122240
C2      min        0.153364  0.574275  0.145641  0.000346  0.424892  0.000000
        std        0.066177  0.024346  0.178869  0.015363  0.344874  0.018169
C3      min        0.298712  0.521224  0.533701  0.000000  0.623036  0.000033
        std        0.225567  0.124146  0.487900  0.000000  0.606600  0.000073
C4      min        0.351008  0.237860  0.620323  0.000000  0.672173  0.087854
        std        0.111448  0.571224  0.608606  0.036295  0.472278  0.659785
C5      min        0.146297  0.552138  0.331996  0.000000  0.466211  0.000090
        std        0.194326  0.573453  0.534196  0.000000  0.437883  0.353524
C6      min        0.002421  1.000000  0.007668  0.000000  0.062308  0.000031
        std        0.023501  1.000000  0.270447  0.000023  0.187364  0.000019
C7      min        0.080381  1.000000  0.158683  0.000000  0.302427  0.001327
        std        0.100712  0.931070  0.581119  0.005190  0.279116  0.003054
C8      min        0.024479  0.013438  1.000000  0.000000  0.352177  0.000789
        std        0.000000  0.000000  0.001770  0.000000  0.000040  0.000000
C9      min        0.381828  1.000000  0.787630  0.000000  0.771786  0.000870
        std        0.150971  0.298936  0.406861  0.231098  0.366801  0.194786

                      Model       NRO        SA       WDO
Problem Statictic
C1      min        0.000093  0.010598  1.000000  0.476115
        std        0.000492  0.014606  1.000000  0.687117
C10     min        0.022789  0.548047  0.741035  0.916712
        std        0.926713  0.182565  0.286119  0.169738
C11     min        0.063103  0.440241  0.926131  0.778790
        std        0.987125  0.364203  0.169204  0.258426
C12     min        0.000000  0.597705  0.710225  0.520718
        std        0.316121  0.010641  0.804025  1.000000
C2      min        0.000920  0.014394  0.867825  1.000000
        std        0.015610  0.000000  1.000000  0.801968
C3      min        0.000116  0.002099  0.939377  1.000000
        std        0.000467  0.003138  1.000000  0.784625
C4      min        0.059172  0.119270  1.000000  0.791301
        std        0.000000  0.014133  0.763445  1.000000
C5      min        0.002413  0.012675  1.000000  0.801923
        std        0.143151  0.015537  1.000000  0.631581
C6      min        0.000025  0.000030  0.112379  0.101660
        std        0.000039  0.000000  0.863534  0.539840
C7      min        0.008593  0.024173  0.517894  0.742514
        std        0.021336  0.000000  1.000000  0.678327
C8      min        0.003163  0.001329  0.117401  0.078040
        std        0.000000  0.000000  1.000000  0.023185
C9      min        0.002309  0.044943  0.971381  0.866793
        std        0.384829  0.000000  1.000000  0.822753

#### Compare Models by Ranking

In [52]:
best_fitness(test_folder="physics/cec22", test_names=c_names, models=physics_model_names)

In [53]:
compute_rank(test_folder="physics/cec22", test_names=c_names)

   Problem   ASO   CDO   EFO    EO  HGSO   MVO   NRO     SA   WDO  Model
0       C1  5.00  7.36  9.08  1.32  6.64  1.68  4.00   9.76  7.16   3.00
1       C2  5.04  6.88  6.16  2.16  7.92  2.08  3.44   9.08  9.92   2.32
2       C3  5.00  6.60  6.44  1.00  7.96  2.00  4.00   9.92  9.08   3.00
3       C4  5.76  4.96  7.68  1.00  7.32  4.16  3.12  10.00  9.00   2.00
4       C5  4.88  6.64  6.64  1.00  8.00  3.32  2.32  10.00  8.72   3.48
5       C6  5.00  9.88  6.20  2.52  6.80  3.08  1.44   9.08  8.04   2.96
6       C7  5.00  9.92  6.32  1.12  6.68  1.88  3.32   8.92  8.16   3.68
7       C8  5.88  5.00  8.80  1.12  7.44  2.00  2.88   9.76  8.00   4.12
8       C9  5.00  8.32  6.20  2.80  6.84  2.80  1.48   9.92  8.72   2.92
9      C10  3.84  6.76  9.08  4.24  6.56  3.00  2.52   8.92  8.68   1.40
10     C11  3.68  6.96  9.92  4.24  6.08  3.92  1.96   8.72  8.24   1.28
11     C12  4.96  9.16  6.04  1.24  7.08  2.52  4.00   8.80  8.76   2.44

#### Compare Models by Signed Test

In [54]:
cec22 = signed_test(test_folder="physics/cec22", test_names=c_names, trial_size=25)
cec22

  Model2  (+)  (-)  Trials
0    ASO   20  280     300
1    CDO   19  281     300
2    EFO    0  300     300
3     EO  203   97     300
4   HGSO    1  299     300
5    MVO  181  119     300
6    NRO  134  166     300
7     SA    1  299     300
8    WDO    2  298     300

### RESULTS OF ALL TESTS

The comparison of the ACSA model and other methods is as follows. (-) indicates how many of the results have the minimum value, that is, the WINNING score.

In [55]:
all = classic + cec22 
all

     Model2  (+)  (-)  Trials
0    ASOASO   33  667     700
1    CDOCDO   39  661     700
2    EFOEFO    0  700     700
3      EOEO  443  257     700
4  HGSOHGSO    4  696     700
5    MVOMVO  312  388     700
6    NRONRO  331  369     700
7      SASA    3  697     700
8    WDOWDO   15  685     700

In [56]:
classic.to_csv('results/physics_classic.csv', index=False)
cec22.to_csv('results/physics_cec.csv', index=False)
all.to_csv('results/physics_total.csv', index=False)